### ISSUE TITLE
CAn you help me understand these errors?

### ISSUE THREAD

**Issue by githubber** [raamattu/osis2usfm#1]
Hi, great utility! If I can get it to work it will save me hours of work. I get these errors:

home:osis2usfm-master home$ sudo python osis2usfm.py nt.xml
Traceback (most recent call last):
  File "osis2usfm.py", line 77, in <module>
    tree = ET.parse(filename)
  File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: mismatched tag: line 50, column 2

Thank you!

**Comment by dancek** [comment]
I'm guessing your XML isn't well-formed. Looks like it's not osis2ufsm that is failing; it's the XML parsing (ElementTree, which is in Python standard library) that fails.
